### ISSUE TITLE
Returning null instead of City object

### ISSUE THREAD

**Issue by ErikSvensson76** [MariaHofstam/JDBC-Assignment#1]
public City add(City city) {
		
		try (Connection conn = DataBase.getConnection();
				PreparedStatement statement = createPreparedStatementAdd(conn, city);){
			
			 statement.executeUpdate();
			 
		}catch (SQLException e) {
			e.printStackTrace();
		}
		
		return null;
	}

also in

        public City update(City city) {
		try (Connection conn = DataBase.getConnection();
				PreparedStatement statement = createPreparedStatementUpdate(conn, city);){
			
			 statement.executeUpdate();
			 
		}catch (SQLException e) {
			e.printStackTrace();
		}
		
		return null;
	}

- Make sure you return a city

**Comment by MariaHofstam** [comment]
Updated
